config/routes.rb
MovitasStyleGuide::Application.routes.draw do
  
  root :to => 'pages#overview', :as => 'overview'
  
  get "pages/overview"

  get "pages/styling", :as => 'styling'

  get "pages/markup", :as => 'markup'
  
  get "pages/branding", :as => 'branding'

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def overview
  end

  def styling
  end

  def markup
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>MovitasStyleGuide</title>
  <%= stylesheet_link_tag    "application" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
  <meta content="width=device-width, initial-scale=1.0, user-scalable=yes" name="viewport" id="viewport">
</head>
<body>
  <header>
    <div id="header">
      <div class="container">
        <div id="logo">
          <a href="/"><img src="/images/logo.png" width="255" height="58" alt="Logo"></a>Living Style Guide
        </div>
      </div>
    </div>
  </header>
  <nav>
    <div id="nav">
      <div class="container">
        <ul class="navigation">
          <li>
            <%= link_to_unless_current "Overview", overview_path %>
          </li>
          <li>
            <%= link_to_unless_current "Branding", branding_path %>
          </li>
          <li>
            <%= link_to_unless_current "Styling(CSS)", styling_path %>
          </li>
          <li>
            <%= link_to_unless_current "Markup(HTML)", markup_path %>
          </li>
        </ul>
      </div>
    </div>
  </nav>
  
  <article>
    <div class="container">
      <%= yield %>
    </div>
  </article>

</body>
<script type="text/javascript">
     SyntaxHighlighter.all()
</script>
</html>

app/views/pages/branding.html.erb
<h1>Branding</h1>
<div class="content">
  <a name="Logo"></a>
  <h2>The Logo Design</h2>
  <div class="section">
    <h3>Primary Logo</h3>
    <p>
    <img src="/images/branding/logo_example.png" alt="Logo Example">
    </p>
    <p>
      <a class="button" href="/resources/logo-vector.eps">Download .eps</a>
    </p>
  </div>
  <div class="section">
    <h3>Specifications</h3>
    <p>
    <img src="/images/branding/logo_margin.png" alt="Logo Example">
    </p>
    <p>
      <span style="color: #00afec;">Blue</span> outline indicates minimum clear space. This area must be kept free of all other elements.
    </p>
    <p>
      The minimum required clear space is 25% of the total height of the logo.
    </p>
  </div>
  <div class="section">
    <h3>Alternative Logo Versions</h3>
    <h4>The logo in solid black</h4>
    <p>
    <img src="/images/branding/logo_example_black.png" alt="Logo Example">
    </p>
    <p>
      <a class="button" href="/resources/logo_black.eps">Download .eps</a>
    </p>
    <h4>The logo in solid white</h4>
    <p>
    <img src="/images/branding/logo_example_white.png" alt="Logo Example">
    </p>
    <p>
      <a class="button" href="/resources/logo_white.eps">Download .eps</a>
    </p>
  </div>
  <div class="section">
    <h3>Minimum Logo Size</h3>
    <p>
    <img src="/images/branding/logo_min_width.png" alt="Logo Example">
    </p>
  </div>
  <div class="section">
    <h3>Social Media Icon and Website Favicon</h3>
    <p>
    <img src="/images/branding/social_media_icon.png" alt="Logo Example">
    </p>
    <p>
      <a href="/resources/logo_social_media.eps">Download .eps</a>
    </p>
  </div>
  <a name="color_palette"></a>
  <h2>The Color Palette </h2>
  <div class="section">
    <h3>Primary Colors</h3>
    <div class="colors">
      <div class="color blue">
      </div>
      <p>
        Pantone DS 238-5 U<br/>
        C: 60 M:5 Y:15 K:25<br/>
        R: 63 G:154 B:170<br/>
        #3f9aaa
      </p>
    </div>
    <div class="colors">
      <div class="color green">
      </div>
      <p>
        Pantone DS 311-3 U<br/>
        C:15 M:0 Y:75 K:20<br/>
        R:181 G:192 B:52<br/>
        #b5c034
      </p>
    </div>
  </div>
  <div class="section">
    <h3>Grayscale Color</h3>
    <div class="colors">
      <div class="color white">
      </div>
      <p>
        C: 0 M:0 Y:0 K:0<br/>
        R: 255 G:255 B:255<br/>
        #FFFFFF
      </p>
    </div>
    <div class="colors">
      <div class="color black">
      </div>
      <p>
        C:0 M:0 Y:0 K:100<br/>
        R:0 G:0 B:0<br/>
        #000000
      </p>
    </div>
  </div>
</div>

app/views/pages/markup.html.erb
<h1>Markup</h1>
<div class="content">
  <h2>HTML</h2>
  <a name="guidelines"></a>
  <div class="section">
    <h3>Guidelines</h3>
    <ul>
      <li>Paragraphs should always be in &lt;p&gt; tags (do not use multiple &lt;br/&gt; to separate paragraphs).</li>
      <li>List should always be in &lt;ul&gt;, &lt;ol&gt;, or &lt;dl&gt; tags.</li>
      <li>Name things semantically. Think about what the object actually is.</li>
    </ul>
  </div>
  <a name="headings"></a>
  <div class="section">
    <h3>Headings</h3>
    <ul>
      <li>&lt;h1&gt; Only use once(not for logos).</li>
      <li>&lt;h1&gt; is for content not for images.</li>
      <li>You may use all other headers as needed.</li>
      <li>Use order of significance as you go down the headers.</li>
      </li>
    </ul>
  </div>
  <a name="specificity"></a>
  <div class="section">
    <h3>Specificity</h3>
    <h4>Id's Vs Classes</h4>
    <ul>
      <li>Id's only use once per page.</li>
      <li>Classes: mark up similar items...similarly.</li>
      <li>Give everything a description.</li>
      <li>Make it make sense for what it does, not what it looks like. (ex: not (redText) use (notice warning))</li>
    </ul>
    
  </div>
  <a name="do_nots"></a>
  <div class="section">
    <h3>Do Nots</h3>
    <h4>Do not give different id's to the same element on different pages.</h4>
    <ul>
      <li>Give them a universal class.</li>
      <li>Creating multiple id's just creates unnecessary code for everyone and becomes a nightmare for maintainability.</li> 
    </ul>
    <h4>The internet is...THE INTERNET</h4>
    <ul>
      <li>Do not use different id's and classes depending on device.</li>
      <li>Do not use device detection use feature detection to account for the future.</li>
      <ul>
        <li>If necessary only apply specific device classes to body tag and keep all other structure the same.</li>
      </ul>
      <li>Do not create extra html when you do not have to.</li>
      <li>Do not put text in ALL CAPS, that can be done with css if necessary.</li> 
    </ul>
    <h4>Do not do:</h4>
    <pre class="brush: plain">
      &lt;div style="clear:both;">&lt;/div>
    </pre>
    <h4>Instead do</h4>
    <pre class="brush: sass">
      //Mixins
      @mixin clearAfter
        &:after
          content: "\0020"
          display: block
          height: 0
          clear: both
          overflow: hidden
          visibility: hidden

      .clearAfter
        +clearAfter
    </pre>
    <p>So in you html you can just add:</p>
    <pre class="brush: plain">
      &lt;div class="clearAfter;">
        &lt;!--Content-->
      &lt;/div>
    </pre>
    <p>This method requires no extra markup</p>
  </div>
</div>

app/views/pages/overview.html.erb
<h1>Overview</h1>
<div class="content">
  <div class="section">
    <h2>Welcome to the Movitas Living Style Guide</h2>
    <p>This style guide is meant to serve as reference for all Movitas branding guidelines, CSS Styling, and HTML Markup. It is meant to be used for all designers and developers working on the Movitas Platform.</p>
  </div>
  <div class="section">
    <h3>The web can be complicated... so lets not be.</h3>
    <ul>
      <li>Make it simple.</li>
      <li>Make it readable.</li>
      <li>Make it understandable.</li>
      <li>Make it maintainable.</li>
    </ul>
  </div>
  <div class="section">
    <h3>Contents:</h3>
    <h4>Branding</h4>
    <ul>
      <li><a href="/pages/branding#logo">Logo</a></li>
      <li><a href="/pages/branding#color_palette">Color Palette</a></li>
      <!-- <li>Fonts</li> -->
    </ul>
    <h4>Styling</h4>
    <ul>
      <li><a href="/pages/styling#file_stack">File Stack</a></li>
      <li><a href="/pages/styling#naming_conventions">Naming Conventions</a></li>
      <li><a href="/pages/styling#sass">SASS</a></li>
      <li><a href="/pages/styling#do_nots">Do Not's</a></li>
    </ul>
    <h4>Markup</h4>
    <ul>
      <li><a href="/pages/markup#guidelines">HTML Guidelines</a></li>
      <li><a href="/pages/markup#headings">Headings</a></li>
      <li><a href="/pages/markup#spceificity">Specificity</a></li>
    </ul>
  </div>
  <div class="section">
    <h4>More coming all the time...</h4>
    <p>To track the status of updates visit <a href="https://trello.com/board/system-updates/4f94b963c30113b97a559e23" target="_blank">System Updates on Trello</a>.</p>
  </div>
</div>

app/views/pages/styling.html.erb
<h1>Styling</h1>
<div class="content">
  <h2>CSS</h2>
  <a name="file_stack"></a>
  <div class="section">
    <h3>File Stack</h3>
    <h4>Current File Stack</h4>
    <p>Our current structure has a common.css file that is used for all businesses and a dynamic.css file with a reset.css imported into it.</p>
    <ul>
      <li>common.css</li> 
      <li>reset.css</li>
      <li>dynamic.css</li>
    </ul>
    <h4>What we should have</h4>
    <p>We should be applying reset.css before the common.css to ensure that we are starting at an even playing field for all browsers.</p>
    <ul>
      <li>reset.css</li>
      <li>common.css</li> 
      <li>dynamic.css</li>
    </ul>
  </div>
  <a name="naming_conventions"></a>
  <div class="section">
    <h3>Naming Conventions</h3>
    <h4>camelCase</h4>
    <p>camelCase, also known as lower camelCase, should be used for all id's and classes.</p>
    <h5>Example</h5>
    <pre class="brush: sass">
    .contentWrap
      //styles here
    </pre>
    <h5>Not:</h5>
    <pre class="brush: sass">
    .content_wrap
      //styles here
      
    .content-wrap
      //styles here
    </pre>
    <h4>Rules</h4>
    <p>Think about long term maintanence when naming classes.</p>
    <p>Always describe classes and id's based on what the are not what they look like.</p>
    <h5>Example:</h5>
    <pre class="brush: sass">
      class="warning"
    </pre>
    <h5>Not:</h5>
    <pre class="brush: sass">
      class="red"
    </pre>
    <p class="note">*All css is written in SASS, which brings us to our next topic...</p>
  </div>
  <a name="sass"></a>
  <div class="section">
    <h3>SASS</h3>
    <p>We use <a href="http://sass-lang.com/" target="_blank">SASS</a> with <a href="http://compass-style.org/" target="_blank">Compass</a> to precompile CSS.</p>
    <h4>With great power comes great responsibility.</h4>
    <p>Do not nest more than three levels down to make your code more readable.</p>
    <pre class="brush: sass">
    .contentWrap
      //Style here
      .content
        //style here
        .section
          //STOP!
    </pre>
    <p>For more information and references visit: <a href="http://sass-lang.com/" target="_blank">sass-lang.com</a> or <a href="http://compass-style.org/" target="_blank">compass-style.org</a></p>
  </div>
  <a name="do_nots"></a>
  <div class="section">
    <h3>Do Nots</h3>
    <h4>Do not use !important</h4>
    <ul>
      <li>!important is a band-aid.</li>
      <li>It is a solution that has not fixed the problem.</li>
      <li>If you find yourself needing to write !important on something it is probably not classified correctly in the html or their is CSS that does not belong in the common.</li>
    </ul>
  </div>
</div>